all:
	nasm -f elf32 -o hello.o hello.asm
	ld -m elf_i386 -o hello.bin hello.o
	
	nasm -f elf32 -o hello2.o hello2.asm
	ld -m elf_i386 -o hello2.bin hello2.o
	
	nasm -f elf32 -o hello3.o hello3.asm
	ld -m elf_i386 -o hello3.bin hello3.o
